apiVersion: apps/v1
kind: Deployment
metadata:
  name: priajiservice
spec:
  selector:
    matchLabels:
      app: priajiservice
  template:
    metadata:
      labels:
        app: priajiservice
    spec:
      containers:
        - name: priajiservice
          image: priajiabror/eureka-server:latest
          command:
            - /bin/sh
            - -c
            - "curl --location --request POST 'http://10.2.62.221:18080/job/priajiservices/build?token=argocd-token' --header 'Authorization: Basic YWRtaW46MTEzMTJhMGEwMDk2YWFjMjMxNmYxNThlMjZkYjZiZWUxYQ==' --header 'Cookie: JSESSIONID.eeba1ccf=node01wdndnnmvb9l0x1orax5wn0fn6.node0'"
          ports:
            - containerPort: 8761