apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
spec:
  containers:
  restartPolicy: Never
    - args:
        - --silent
        - --output
        - '/tmp/http_code'
        - --location
        - --request
        - POST
        - http://10.2.62.221:18080/job/priajiservices/build?token=argocd-token
        - --header
        - 'Authorization: Basic YWRtaW46MTEzMTJhMGEwMDk2YWFjMjMxNmYxNThlMjZkYjZiZWUxYQ=='
        - --header
        - 'Cookie: JSESSIONID.eeba1ccf=node01wdndnnmvb9l0x1orax5wn0fn6.node0'
        - --write-out
        - '%{http_code}'
      command:
        - curl
      image: curlimages/curl:latest
      name: curl-container