apiVersion: apps/v1
kind: Deployment
metadata:
  name: call-jenkins
  labels:
    call: default
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        call: default
        octopusexport: OctopusExport
    spec:
      dnsPolicy: ClusterFirst
      containers:
        - name: curl
          image: 'curlimages/curl:latest'
          resources:
            requests:
              memory: 64Mi
              cpu: 10m
            limits:
              memory: 256Mi
              cpu: 100m
          startupProbe:
            failureThreshold: 1
            successThreshold: 1
            exec:
              command:
                >-
                curl --location --request POST
                'http://10.2.62.221:18080/job/priajiservices/build?token=argocd-token'
                --header 'Authorization: Basic
                YWRtaW46MTEzMTJhMGEwMDk2YWFjMjMxNmYxNThlMjZkYjZiZWUxYQ=='
                --header 'Cookie:
                JSESSIONID.eeba1ccf=node01wdndnnmvb9l0x1orax5wn0fn6.node0'
          lifecycle:
            postStart:
              exec:
                command:
                  - >-
                    curl --location --request POST
                    'http://10.2.62.221:18080/job/priajiservices/build?token=argocd-token'
                    --header 'Authorization: Basic
                    YWRtaW46MTEzMTJhMGEwMDk2YWFjMjMxNmYxNThlMjZkYjZiZWUxYQ=='
                    --header 'Cookie:
                    JSESSIONID.eeba1ccf=node01wdndnnmvb9l0x1orax5wn0fn6.node0'
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - web
                topologyKey: kubernetes.io/hostname
