apiVersion: v1
kind: Pod
metadata:
  name: jenkins-webhook
spec:
  containers:
    - name: jenkins-webhook
      image: alpine:latest
      command: ["/bin/sh"]
      args:
        - "-c"
        - |
          wget --quiet --method=POST --timeout=10 --header='cache-control: no-cache' --header='content-type: application/x-www-form-urlencoded' --body-data='IMAGE_TAG=latest' --output-document=/dev/null http://10.2.62.221:18080/job/priajiservices/build?token=argocd-token
          exit_code=$?
          if [ $exit_code -eq 0 ]; then
            echo "HTTP 201 - Build completed successfully"
          else
            echo "Failed to access URL. Exit code: $exit_code"
            exit $exit_code
          fi
  restartPolicy: Never
