---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-webhook
spec:
  externalName: http://10.2.62.221:18080/job/priajiservices/buildWithParameters?token=argocd-token
  ports:
    - port: 80
      targetPort: 18080
  type: ExternalName
---
apiVersion: v1
data:
  TOKEN: 11312a0a0096aac2316f158e26db6bee1a
kind: ConfigMap
metadata:
  name: jenkins-webhook-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-webhook
  template:
    metadata:
      labels:
        app: jenkins-webhook
    spec:
      containers:
        - command:
            - /bin/sleep
            - infinity
          env:
            - name: TOKEN
              valueFrom:
                configMapKeyRef:
                  key: TOKEN
                  name: jenkins-webhook-config
          image: curlimages/curl:latest
          name: jenkins-webhook
