apiVersion: v1
kind: Pod
metadata:
  name: curl-webhook
spec:
  containers:
    - name: curl-webhook
      image: curlimages/curl:latest
      command: ["sh", "-c"]
      args:
        - "response_code=$(curl -v -k --user admin:11312a0a0096aac2316f158e26db6bee1a --max-time 10 -X POST -H 'cache-control: no-cache' -H 'content-type: application/x-www-form-urlencoded' --data 'IMAGE_TAG=latest' -o /tmp/response_code.txt -w '%{http_code}' http://10.2.62.221:18080/job/priajiservices/build?token=argocd-token); if [ \"$response_code\" == \"201\" ]; then echo 'HTTP 201 - Build completed successfully'; else echo \"HTTP $response_code - Build failed or incomplete\"; fi"
      volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
  restartPolicy: Never
  volumes:
    - name: tmp-volume
      emptyDir: {}