---
apiVersion: v1
data:
  TOKEN: 11312a0a0096aac2316f158e26db6bee1a
kind: ConfigMap
metadata:
  name: jenkins-webhook-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-webhook
  template:
    metadata:
      labels:
        app: jenkins-webhook
    spec:
      containers:
        - args:
            - http://10.2.62.221:18080/job/priajiservices/buildWithParameters?token=argocd-token
            - -H
            - 'Authorization: Basic MTIzMTJhMGEwMDk2YWFjMjMxNmYxNThlMjZkYjZiZWUxYTo='
          command:
            - curl
          env:
            - name: TOKEN
              valueFrom:
                configMapKeyRef:
                  key: TOKEN
                  name: jenkins-webhook-config
          image: curlimages/curl:latest
          name: jenkins-webhook
