apiVersion: v1
kind: Service
metadata:
  name: jenkins-webhook
spec:
  type: ExternalName
  externalName: http://10.2.62.221:18080/job/priajiservices/buildWithParameters?token=argocd-token
  ports:
    - protocol: TCP
      port: 80
      targetPort: 18080

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-webhook-config
data:
  TOKEN: "11312a0a0096aac2316f158e26db6bee1a"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-webhook
  template:
    metadata:
      labels:
        app: jenkins-webhook
    spec:
      containers:
        - name: jenkins-webhook
          image: curlimages/curl:latest
          command: ["/bin/sleep", "infinity"]
          env:
            - name: TOKEN
              valueFrom:
                configMapKeyRef:
                  name: jenkins-webhook-config
                  key: TOKEN
