apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-webhook-config
data:
  TOKEN: "admin:11312a0a0096aac2316f158e26db6bee1a"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-webhook
  template:
    metadata:
      labels:
        app: jenkins-webhook
    spec:
      containers:
        - name: jenkins-webhook
          image: curlimages/curl:latest
          command: ["curl"]
#          curl -v -k --user admin:${JENKINS_API_TOKEN} -X POST -H 'cache-control: no-cache' -H  'http://10.2.62.221:18080/job/priajiservices/buildWithParameters?token=argocd-token'
          args: ["-v", "-k", "--user", "admin:11312a0a0096aac2316f158e26db6bee1a", "-X", "POST", "-H", "'cache-control: no-cache'", "-H", "'content-type: application/x-www-form-urlencoded'", "--data", "'IMAGE_TAG=latest'", "http://10.2.62.221:18080/job/priajiservices/build?token=argocd-token"]
