apiVersion: batch/v1
kind: Job
metadata:
  name: call-jenkins
  namespace: default
spec:
  ttlSecondsAfterFinished: 10 # deleted the finished pod after 2 minutes
  backoffLimit: 6 # default value
  parallelism: 2
  completions: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: curl
          image: curlimages/curl:latest
          imagePullPolicy: Always
          command:
#            - "/bin/bash"
#            - "-c"
#            - curl
#            - -silent
#            - -output
#            - '/tmp/http_code'
#            - -location
#            - -request
#            - POST
#            - http://10.2.62.221:18080/job/priajiservices/build?token=argocd-token
#            - -header
#            - 'Authorization: Basic YWRtaW46MTEzMTJhMGEwMDk2YWFjMjMxNmYxNThlMjZkYjZiZWUxYQ=='
#            - -header
#            - 'Cookie: JSESSIONID.eeba1ccf=node01wdndnnmvb9l0x1orax5wn0fn6.node0'
#            - -write-out
#            - '%{http_code}'
            - "curl --location --request POST 'http://10.2.62.221:18080/job/priajiservices/build?token=argocd-token' --header 'Authorization: Basic YWRtaW46MTEzMTJhMGEwMDk2YWFjMjMxNmYxNThlMjZkYjZiZWUxYQ==' --header 'Cookie: JSESSIONID.eeba1ccf=node01wdndnnmvb9l0x1orax5wn0fn6.node0'"
