apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
spec:
  containers:
    - name: curl-container
      args:
        - --silent
        - --output
        - '/tmp/http_code'
        - --location
        - --request
        - POST
        - http://10.2.62.221:18080/job/priajiservices/build?token=argocd-token
        - --header
        - 'Authorization: Basic YWRtaW46MTEzMTJhMGEwMDk2YWFjMjMxNmYxNThlMjZkYjZiZWUxYQ=='
        - --header
        - 'Cookie: JSESSIONID.eeba1ccf=node01wdndnnmvb9l0x1orax5wn0fn6.node0'
        - --write-out
        - '%{http_code}'
      command:
        - curl
      image: curlimages/curl:latest
   - name: action-container
     image: alpine:latest
     command: [ "/bin/sh" ]
     args:
       - "-c"
       - |
         if [ -f "/tmp/http_code" ]; then
           HTTP_STATUS=$(cat "/tmp/http_code")
           if [ "$HTTP_STATUS" = "201" ]; then
             echo "HTTP 201 - Build completed successfully"
             # Tambahkan tindakan tambahan di sini jika diperlukan
           else
             echo "HTTP $HTTP_STATUS - Build failed or incomplete"
             # Tambahkan tindakan tambahan di sini jika diperlukan
           fi
         else
           echo "Error: HTTP code file not found"
           exit 1
         fi