server:
  port: 18083

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**
          filters:
            - AuthenticationFilter

        - id: fraud
          uri: lb://FRAUD
          predicates:
            - Path=/api/v1/fraud-check/**
          filters:
            - AuthenticationFilter

        - id: notification
          uri: lb://NOTIFICATION
          predicates:
            - Path=/api/v1/notification/**
          filters:
            - AuthenticationFilter

        - id: security
          uri: lb://SECURITY
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true